In [25]:
import numpy as np
import cv2

In [26]:
img = np.array([[49,6,9,9,39,45],
                [54,17,58,25,2,45],
                [8,33,57,55,51,24],
                [55,57,29,48,56,39],
                [38,58,38,58,41,10]])
img2 = np.pad(img, (1,1), 'constant')
result = np.zeros((img.shape[0], img.shape[1]))

kernel = np.ones((3,3))

temps = []

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        temp1 = kernel[1,1] * img2[i+1,j+1]
        temp2 = kernel[1,0] * img2[i+1,j]
        temp3 = kernel[1,2] * img2[i+1,j-1]
        
        temp4 = kernel[0,0] * img2[i,j-1]
        temp5 = kernel[0,1] * img2[i,j]
        temp6 = kernel[0,2] * img2[i,j+1]
        
        temp7 = kernel[2,0] * img2[i+1,j]
        temp8 = kernel[2,1] * img2[i+1,j+1]
        temp9 = kernel[2,2] * img2[i+1,j-1]


In [32]:
img2

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 49,  6,  9,  9, 39, 45,  0],
       [ 0, 54, 17, 58, 25,  2, 45,  0],
       [ 0,  8, 33, 57, 55, 51, 24,  0],
       [ 0, 55, 57, 29, 48, 56, 39,  0],
       [ 0, 38, 58, 38, 58, 41, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [17]:
kernel

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
img = np.array([[49,6,9,9,39,45],
                [54,17,58,25,2,45],
                [8,33,57,55,51,24],
                [55,57,29,48,56,39],
                [38,58,38,58,41,10]])
img2 = np.pad(img, (1,1), 'constant')
result = np.zeros((img.shape[0], img.shape[1]))

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        area = img2[i:i+3, j:j+3]
        area_flat = area.flatten()
        sort_area = np.sort(area_flat)
        
        result[i,j] = sort_area[4]
        

In [52]:
result

array([[ 0.,  9.,  9.,  9.,  9.,  0.],
       [ 8., 33., 25., 39., 39., 24.],
       [17., 54., 48., 51., 45., 24.],
       [33., 38., 55., 51., 48., 24.],
       [ 0., 38., 38., 38., 39.,  0.]])

In [53]:
img = np.array([[49,6,9,9,39,45],
                [54,17,58,25,2,45],
                [8,33,57,55,51,24],
                [55,57,29,48,56,39],
                [38,58,38,58,41,10]])
img2 = np.pad(img, (1,1), 'constant')
result = np.zeros((img.shape[0], img.shape[1]))

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        area = img2[i:i+3, j:j+3]
        added = np.sum(area)
        result[i,j] = added / 9

In [54]:
result

array([[14.        , 21.44444444, 13.77777778, 15.77777778, 18.33333333,
        14.55555556],
       [18.55555556, 32.33333333, 29.88888889, 33.88888889, 32.77777778,
        22.88888889],
       [24.88888889, 40.88888889, 42.11111111, 42.33333333, 38.33333333,
        24.11111111],
       [27.66666667, 41.44444444, 48.11111111, 48.11111111, 42.44444444,
        24.55555556],
       [23.11111111, 30.55555556, 32.        , 30.        , 28.        ,
        16.22222222]])

In [56]:
result = np.zeros((img.shape[0], img.shape[1]))
for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        print(img[i,j])
        if (img[i,j] >= 50 and img[i,j] <= 100):
            result[i,j] = 1
        else:
            result[i,j] = 0

result

49
6
9
9
39
45
54
17
58
25
2
45
8
33
57
55
51
24
55
57
29
48
56
39
38
58
38
58
41
10


array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.]])

In [61]:
#playground to generate basic idea of color image
result = np.zeros((img.shape[0], img.shape[1],3))

r = np.array([[120,130,180,190,200],
              [44,33,55,99,122],
               [255,250,240,230,255],
               [120,230,120,200,128],
               [120,130,180,190,200]])
              
g = np.array([[255,250,240,230,255],
              [44,33,55,99,122],
               [255,250,240,230,255],
               [120,230,120,200,128],
               [120,130,180,190,200]]
              )
b = np.array([[12,22,44,66,77],
              [44,33,55,99,122],
               [120,230,120,200,128],
              [255,250,240,230,255],
               [120,130,180,190,200]]
              )
img = np.dstack((r,g,b))
# plt.imshow(img)

In [63]:
for i in range(img.shape[1]):
    for j in range(img.shape[2]):
        if (img[i,j,0]>50 and img[i,j,0]<=150):
            result[i,j,0] = 255
        if (img[i,j,1]>200 and img[i,j,1]<=255):
            result[i,j,1] = 0
            

In [64]:
result

array([[[255.,   0.,   0.],
        [255.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [255.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[255.,   0.,   0.],
        [  0.,   0.,   0.],
        [255.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[255.,   0.,   0.],
        [255.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]]])